using System.Collections.Generic;
using System.Text;
using CrudKit.SourceGen.Models;

namespace CrudKit.SourceGen.Generators;

/// <summary>
/// Generates a Create DTO positional record from entity metadata using the configured naming convention.
/// Returns <c>null</c> when the entity is ReadOnly or EnableCreate is false.
/// </summary>
internal static class CreateDtoGenerator
{
    /// <summary>
    /// Builds the source text for the CreateDto file.
    /// Returns <c>null</c> when no file should be emitted.
    /// </summary>
    public static string? Generate(EntityMetadata entity, NamingConvention naming)
    {
        if (!entity.IsCreateEnabled)
            return null;

        // Properties eligible for CreateDto: not system, not [Protected]
        var props = new List<PropertyMetadata>();
        foreach (var p in entity.Properties)
        {
            if (!p.IsProtected)
                props.Add(p);
        }

        // Required parameters must appear before optional ones in positional records
        props.Sort((a, b) =>
        {
            bool aRequired = a.IsRequired;
            bool bRequired = b.IsRequired;
            if (aRequired && !bRequired) return -1;
            if (!aRequired && bRequired) return 1;
            return 0; // preserve relative order within same group
        });

        // Collect additional usings from property types (e.g. enum namespaces)
        var additionalUsings = new HashSet<string>();
        foreach (var p in props)
        {
            if (p.FullTypeName != p.TypeName && p.FullTypeName.Contains("."))
            {
                var ns = p.FullTypeName.Substring(0, p.FullTypeName.LastIndexOf('.'));
                if (!ns.StartsWith("System") && ns != entity.Namespace)
                    additionalUsings.Add(ns);
            }
            // Also handle nullable enum types: Namespace.EnumType? → Namespace
            var cleanFullType = p.FullTypeName.TrimEnd('?');
            var cleanTypeName = p.TypeName.TrimEnd('?');
            if (cleanFullType != cleanTypeName && cleanFullType.Contains("."))
            {
                var ns = cleanFullType.Substring(0, cleanFullType.LastIndexOf('.'));
                if (!ns.StartsWith("System") && ns != entity.Namespace)
                    additionalUsings.Add(ns);
            }
        }

        string className = naming.FormatCreateDtoName(entity.Name);

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by CrudKit.SourceGen — do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.ComponentModel.DataAnnotations;");
        foreach (var ns in additionalUsings)
            sb.AppendLine($"using {ns};");
        sb.AppendLine();
        sb.AppendLine($"namespace {entity.Namespace}.Dtos;");
        sb.AppendLine();
        sb.Append($"public sealed record {className}(");

        if (props.Count == 0)
        {
            sb.AppendLine(");");
        }
        else
        {
            sb.AppendLine();
            for (int i = 0; i < props.Count; i++)
            {
                var p = props[i];
                bool isLast = i == props.Count - 1;

                // Emit validation attributes on the parameter
                if (p.IsRequired)
                    sb.AppendLine("    [Required]");
                if (p.HasMaxLength)
                    sb.AppendLine($"    [MaxLength({p.MaxLength})]");
                if (p.HasRange)
                    sb.AppendLine($"    [Range({p.RangeMin}, {p.RangeMax})]");

                string typeName = p.IsNullable && !p.TypeName.EndsWith("?")
                    ? p.TypeName + "?"
                    : p.TypeName;

                string defaultVal = GetDefaultValue(p);
                sb.Append($"    {typeName} {p.Name}");
                if (!string.IsNullOrEmpty(defaultVal))
                    sb.Append($" = {defaultVal}");

                if (!isLast)
                    sb.AppendLine(",");
                else
                    sb.AppendLine(");");
            }
        }

        return sb.ToString();
    }

    // Returns a sensible default expression so the record compiles even when not all
    // parameters are required.  Required props get no default.
    private static string GetDefaultValue(PropertyMetadata p)
    {
        if (p.IsRequired)
            return string.Empty;

        if (p.IsNullable)
            return "null";

        // Value-type defaults
        switch (p.TypeName)
        {
            case "string": return "\"\"";
            case "int":
            case "long":
            case "short":
            case "byte":
            case "decimal":
            case "float":
            case "double": return "default";
            case "bool": return "false";
            case "Guid": return "default";
            default: return "default";
        }
    }
}
