using System.Collections.Generic;
using System.Text;
using CrudKit.SourceGen.Models;

namespace CrudKit.SourceGen.Generators;

/// <summary>
/// Generates <c>CrudKitMappers.g.cs</c> containing an <c>AddAllCrudMappers()</c>
/// extension on <c>IServiceCollection</c> that registers all generated mapper classes.
/// DTO and mapper type names are resolved via <see cref="NamingConvention"/>.
/// </summary>
internal static class DiRegistrationGenerator
{
    public static string Generate(IReadOnlyList<EntityMetadata> entities, NamingConvention naming)
    {
        if (entities.Count == 0)
            return string.Empty;

        var namespaces = new SortedSet<string>(System.StringComparer.Ordinal);
        foreach (var e in entities)
        {
            namespaces.Add($"{e.Namespace}.Mappers");
            namespaces.Add($"{e.Namespace}.Dtos");
            namespaces.Add(e.Namespace);
        }

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by CrudKit.SourceGen — do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using CrudKit.Core.Interfaces;");
        foreach (var ns in namespaces)
            sb.AppendLine($"using {ns};");
        sb.AppendLine();

        string rootNs = entities[0].Namespace;
        sb.AppendLine($"namespace {rootNs};");
        sb.AppendLine();
        sb.AppendLine("public static class CrudKitMappers");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all CrudKit-generated mapper implementations as scoped services.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddAllCrudMappers(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var entity in entities)
        {
            bool hasCreate = entity.IsCreateEnabled;
            bool hasUpdate = entity.IsUpdateEnabled;

            string n      = entity.Name;
            string create = naming.FormatCreateDtoName(n);
            string update = naming.FormatUpdateDtoName(n);
            string resp   = naming.FormatResponseDtoName(n);
            string mapper = naming.FormatMapperName(n);

            if (hasCreate && hasUpdate)
            {
                // Full CRUD: register as ICrudMapper, then forward individual interfaces
                sb.AppendLine($"        services.AddScoped<ICrudMapper<{n}, {create}, {update}, {resp}>, {mapper}>();");
                sb.AppendLine($"        services.AddScoped<IResponseMapper<{n}, {resp}>>(sp =>");
                sb.AppendLine($"            sp.GetRequiredService<ICrudMapper<{n}, {create}, {update}, {resp}>>());");
                sb.AppendLine($"        services.AddScoped<ICreateMapper<{n}, {create}>>(sp =>");
                sb.AppendLine($"            sp.GetRequiredService<ICrudMapper<{n}, {create}, {update}, {resp}>>());");
                sb.AppendLine($"        services.AddScoped<IUpdateMapper<{n}, {update}>>(sp =>");
                sb.AppendLine($"            sp.GetRequiredService<ICrudMapper<{n}, {create}, {update}, {resp}>>());");
            }
            else if (!hasCreate && !hasUpdate)
            {
                // ReadOnly: only IResponseMapper
                sb.AppendLine($"        services.AddScoped<IResponseMapper<{n}, {resp}>, {mapper}>();");
            }
            else if (hasCreate)
            {
                // Update disabled: IResponseMapper + ICreateMapper
                sb.AppendLine($"        services.AddScoped<IResponseMapper<{n}, {resp}>, {mapper}>();");
                sb.AppendLine($"        services.AddScoped<ICreateMapper<{n}, {create}>>(sp =>");
                sb.AppendLine($"            (ICreateMapper<{n}, {create}>)sp.GetRequiredService<IResponseMapper<{n}, {resp}>>());");
            }
            else
            {
                // Create disabled: IResponseMapper + IUpdateMapper
                sb.AppendLine($"        services.AddScoped<IResponseMapper<{n}, {resp}>, {mapper}>();");
                sb.AppendLine($"        services.AddScoped<IUpdateMapper<{n}, {update}>>(sp =>");
                sb.AppendLine($"            (IUpdateMapper<{n}, {update}>)sp.GetRequiredService<IResponseMapper<{n}, {resp}>>());");
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
