using System.Collections.Generic;
using System.Text;
using CrudKit.SourceGen.Models;

namespace CrudKit.SourceGen.Generators;

/// <summary>
/// Generates <c>CrudKitMappers.g.cs</c> containing an <c>AddAllCrudMappers()</c>
/// extension on <c>IServiceCollection</c> that registers all generated mapper classes.
/// </summary>
internal static class DiRegistrationGenerator
{
    public static string Generate(IReadOnlyList<EntityMetadata> entities)
    {
        if (entities.Count == 0)
            return string.Empty;

        var namespaces = new SortedSet<string>(System.StringComparer.Ordinal);
        foreach (var e in entities)
        {
            namespaces.Add($"{e.Namespace}.Mappers");
            namespaces.Add($"{e.Namespace}.Dtos");
            namespaces.Add(e.Namespace);
        }

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by CrudKit.SourceGen — do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.Extensions.DependencyInjection;");
        sb.AppendLine("using CrudKit.Core.Interfaces;");
        foreach (var ns in namespaces)
            sb.AppendLine($"using {ns};");
        sb.AppendLine();

        string rootNs = entities[0].Namespace;
        sb.AppendLine($"namespace {rootNs};");
        sb.AppendLine();
        sb.AppendLine("public static class CrudKitMappers");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>");
        sb.AppendLine("    /// Registers all CrudKit-generated mapper implementations as scoped services.");
        sb.AppendLine("    /// </summary>");
        sb.AppendLine("    public static IServiceCollection AddAllCrudMappers(this IServiceCollection services)");
        sb.AppendLine("    {");

        foreach (var entity in entities)
        {
            bool hasCreate = entity.IsCreateEnabled;
            bool hasUpdate = entity.IsUpdateEnabled;

            if (hasCreate && hasUpdate)
            {
                // Full CRUD: register as ICrudMapper, then forward individual interfaces
                sb.AppendLine($"        services.AddScoped<ICrudMapper<{entity.Name}, Create{entity.Name}, Update{entity.Name}, {entity.Name}Response>, {entity.Name}Mapper>();");
                sb.AppendLine($"        services.AddScoped<IResponseMapper<{entity.Name}, {entity.Name}Response>>(sp =>");
                sb.AppendLine($"            sp.GetRequiredService<ICrudMapper<{entity.Name}, Create{entity.Name}, Update{entity.Name}, {entity.Name}Response>>());");
                sb.AppendLine($"        services.AddScoped<ICreateMapper<{entity.Name}, Create{entity.Name}>>(sp =>");
                sb.AppendLine($"            sp.GetRequiredService<ICrudMapper<{entity.Name}, Create{entity.Name}, Update{entity.Name}, {entity.Name}Response>>());");
                sb.AppendLine($"        services.AddScoped<IUpdateMapper<{entity.Name}, Update{entity.Name}>>(sp =>");
                sb.AppendLine($"            sp.GetRequiredService<ICrudMapper<{entity.Name}, Create{entity.Name}, Update{entity.Name}, {entity.Name}Response>>());");
            }
            else if (!hasCreate && !hasUpdate)
            {
                // ReadOnly: only IResponseMapper
                sb.AppendLine($"        services.AddScoped<IResponseMapper<{entity.Name}, {entity.Name}Response>, {entity.Name}Mapper>();");
            }
            else if (hasCreate)
            {
                // Update disabled: IResponseMapper + ICreateMapper
                sb.AppendLine($"        services.AddScoped<IResponseMapper<{entity.Name}, {entity.Name}Response>, {entity.Name}Mapper>();");
                sb.AppendLine($"        services.AddScoped<ICreateMapper<{entity.Name}, Create{entity.Name}>>(sp =>");
                sb.AppendLine($"            (ICreateMapper<{entity.Name}, Create{entity.Name}>)sp.GetRequiredService<IResponseMapper<{entity.Name}, {entity.Name}Response>>());");
            }
            else
            {
                // Create disabled: IResponseMapper + IUpdateMapper
                sb.AppendLine($"        services.AddScoped<IResponseMapper<{entity.Name}, {entity.Name}Response>, {entity.Name}Mapper>();");
                sb.AppendLine($"        services.AddScoped<IUpdateMapper<{entity.Name}, Update{entity.Name}>>(sp =>");
                sb.AppendLine($"            (IUpdateMapper<{entity.Name}, Update{entity.Name}>)sp.GetRequiredService<IResponseMapper<{entity.Name}, {entity.Name}Response>>());");
            }
        }

        sb.AppendLine("        return services;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
