using System.Collections.Generic;
using System.Text;
using CrudKit.SourceGen.Models;

namespace CrudKit.SourceGen.Generators;

/// <summary>
/// Generates <c>CrudKitEndpoints.g.cs</c> containing a <c>MapAllCrudEndpoints()</c>
/// extension method on <c>IEndpointRouteBuilder</c>.
/// Each entity uses <c>MapCrudEndpoints</c> (full CRUD with 3 generic params) or
/// <c>MapCrudEndpoints</c> (read-only with 1 generic param) depending on its operation flags.
/// DTO type names are discovered from user-provided [CreateDtoFor] / [UpdateDtoFor] attributes.
/// </summary>
internal static class EndpointMappingGenerator
{
    public static string Generate(
        IReadOnlyList<EntityMetadata> entities,
        IReadOnlyDictionary<string, string> createDtoFqnMap,
        IReadOnlyDictionary<string, string> updateDtoFqnMap)
    {
        if (entities.Count == 0)
            return string.Empty;

        // Collect distinct namespaces used by entity types
        var namespaces = new SortedSet<string>(System.StringComparer.Ordinal);
        foreach (var e in entities)
        {
            namespaces.Add(e.Namespace);
            namespaces.Add($"{e.Namespace}.Hooks");
        }

        // Add namespaces from user-provided DTO FQNs
        foreach (var fqn in createDtoFqnMap.Values)
        {
            var ns = GetNamespace(fqn);
            if (ns != null) namespaces.Add(ns);
        }
        foreach (var fqn in updateDtoFqnMap.Values)
        {
            var ns = GetNamespace(fqn);
            if (ns != null) namespaces.Add(ns);
        }

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by CrudKit.SourceGen — do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Builder;");
        sb.AppendLine("using CrudKit.Api.Endpoints;");
        foreach (var ns in namespaces)
            sb.AppendLine($"using {ns};");
        sb.AppendLine();

        // Determine the common namespace (use first entity's namespace root)
        string rootNs = entities[0].Namespace;
        sb.AppendLine($"namespace {rootNs};");
        sb.AppendLine();
        sb.AppendLine("public static class CrudKitEndpoints");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Maps all CrudKit CRUD endpoints discovered by source generation.</summary>");
        sb.AppendLine("    public static WebApplication MapAllCrudEndpoints(this WebApplication app)");
        sb.AppendLine("    {");

        foreach (var entity in entities)
        {
            // Determine which mapper overload to call
            if (entity.ReadOnly || (!entity.IsCreateEnabled && !entity.IsUpdateEnabled))
            {
                // Read-only: 1 type param, no route (derived from [CrudEntity(Resource=...)])
                sb.AppendLine($"        app.MapCrudEndpoints<{entity.FullName}>();");
            }
            else
            {
                // Full CRUD needs user-provided DTO FQNs
                bool hasCreate = createDtoFqnMap.TryGetValue(entity.Name, out var createFqn);
                bool hasUpdate = updateDtoFqnMap.TryGetValue(entity.Name, out var updateFqn);

                if (hasCreate && hasUpdate)
                {
                    sb.AppendLine($"        app.MapCrudEndpoints<{entity.FullName}, {createFqn}, {updateFqn}>();");
                }
                else
                {
                    // Fall back to entity-only overload when DTO attributes are missing
                    sb.AppendLine($"        app.MapCrudEndpoints<{entity.FullName}>();");
                }
            }
        }

        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }

    private static string? GetNamespace(string fqn)
    {
        var lastDot = fqn.LastIndexOf('.');
        return lastDot > 0 ? fqn.Substring(0, lastDot) : null;
    }
}
