using System.Collections.Generic;
using System.Text;
using CrudKit.SourceGen.Models;

namespace CrudKit.SourceGen.Generators;

/// <summary>
/// Generates <c>CrudKitEndpoints.g.cs</c> containing a <c>MapAllCrudEndpoints()</c>
/// extension method on <c>IEndpointRouteBuilder</c>.
/// Each entity uses <c>MapCrudEndpoints</c> (full CRUD with 3 generic params) or
/// <c>MapCrudEndpoints</c> (read-only with 1 generic param) depending on its operation flags.
/// </summary>
internal static class EndpointMappingGenerator
{
    public static string Generate(IReadOnlyList<EntityMetadata> entities)
    {
        if (entities.Count == 0)
            return string.Empty;

        // Collect distinct namespaces used by entity types
        var namespaces = new SortedSet<string>(System.StringComparer.Ordinal);
        foreach (var e in entities)
        {
            namespaces.Add(e.Namespace);
            namespaces.Add($"{e.Namespace}.Dtos");
            namespaces.Add($"{e.Namespace}.Mappers");
            namespaces.Add($"{e.Namespace}.Hooks");
        }

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by CrudKit.SourceGen — do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using Microsoft.AspNetCore.Routing;");
        sb.AppendLine("using CrudKit.Api;");
        foreach (var ns in namespaces)
            sb.AppendLine($"using {ns};");
        sb.AppendLine();

        // Determine the common namespace (use first entity's namespace root)
        string rootNs = entities[0].Namespace;
        sb.AppendLine($"namespace {rootNs};");
        sb.AppendLine();
        sb.AppendLine("public static class CrudKitEndpoints");
        sb.AppendLine("{");
        sb.AppendLine("    /// <summary>Maps all CrudKit CRUD endpoints discovered by source generation.</summary>");
        sb.AppendLine("    public static IEndpointRouteBuilder MapAllCrudEndpoints(this IEndpointRouteBuilder app)");
        sb.AppendLine("    {");

        foreach (var entity in entities)
        {
            // Determine which mapper overload to call
            if (entity.ReadOnly || (!entity.IsCreateEnabled && !entity.IsUpdateEnabled))
            {
                // Read-only: only GET endpoints
                sb.AppendLine($"        app.MapCrudEndpoints<{entity.Name}, {entity.Name}Response, {entity.Name}Mapper, {entity.Name}Hooks>();");
            }
            else if (entity.IsCreateEnabled && entity.IsUpdateEnabled)
            {
                sb.AppendLine($"        app.MapCrudEndpoints<{entity.Name}, Create{entity.Name}, Update{entity.Name}, {entity.Name}Response, {entity.Name}Mapper, {entity.Name}Hooks>();");
            }
            else if (entity.IsCreateEnabled && !entity.IsUpdateEnabled)
            {
                sb.AppendLine($"        app.MapCreateOnlyEndpoints<{entity.Name}, Create{entity.Name}, {entity.Name}Response, {entity.Name}Mapper, {entity.Name}Hooks>();");
            }
            else
            {
                // EnableUpdate only (no create)
                sb.AppendLine($"        app.MapUpdateOnlyEndpoints<{entity.Name}, Update{entity.Name}, {entity.Name}Response, {entity.Name}Mapper, {entity.Name}Hooks>();");
            }
        }

        sb.AppendLine("        return app;");
        sb.AppendLine("    }");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
