using System.Text;
using CrudKit.SourceGen.Models;

namespace CrudKit.SourceGen.Generators;

/// <summary>
/// Generates a <c>partial class {Name}Hooks : ICrudHooks&lt;{Name}&gt;</c> stub.
/// The partial class is intentionally empty — developers fill it in.
/// </summary>
internal static class HookStubGenerator
{
    public static string Generate(EntityMetadata entity)
    {
        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by CrudKit.SourceGen — do not edit manually.");
        sb.AppendLine("// Rename this file and remove the partial keyword to customize hooks.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine($"using {entity.Namespace};");
        sb.AppendLine("using CrudKit.Core.Interfaces;");
        sb.AppendLine();
        sb.AppendLine($"namespace {entity.Namespace}.Hooks;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>");
        sb.AppendLine($"/// Hook stub for <see cref=\"{entity.Name}\"/>.");
        sb.AppendLine($"/// Override methods from <see cref=\"ICrudHooks{{T}}\"/> as needed.");
        sb.AppendLine($"/// </summary>");
        sb.AppendLine($"public partial class {entity.Name}Hooks : ICrudHooks<{entity.Name}>");
        sb.AppendLine("{");
        sb.AppendLine("    // Override BeforeCreate, AfterCreate, BeforeUpdate, AfterUpdate,");
        sb.AppendLine("    // BeforeDelete, AfterDelete, ApplyScope, and ApplyIncludes as needed.");
        sb.AppendLine("}");

        return sb.ToString();
    }
}
