using System.Collections.Generic;
using System.Text;
using CrudKit.SourceGen.Models;

namespace CrudKit.SourceGen.Generators;

/// <summary>
/// Generates <c>{Name}Mapper</c> implementing the appropriate mapper interface(s):
/// <list type="bullet">
///   <item>All CRUD enabled → <c>ICrudMapper&lt;TEntity, TCreate, TUpdate, TResponse&gt;</c></item>
///   <item>ReadOnly → <c>IResponseMapper&lt;TEntity, TResponse&gt;</c></item>
///   <item>Create disabled → <c>IResponseMapper</c> + <c>IUpdateMapper</c></item>
///   <item>Update disabled → <c>IResponseMapper</c> + <c>ICreateMapper</c></item>
/// </list>
/// </summary>
internal static class MapperGenerator
{
    public static string Generate(EntityMetadata entity)
    {
        bool hasCreate = entity.IsCreateEnabled;
        bool hasUpdate = entity.IsUpdateEnabled;

        // Determine which interface(s) to implement
        string interfaceList = BuildInterfaceList(entity, hasCreate, hasUpdate);

        var responseProps = BuildResponseProps(entity);
        var assignments   = BuildAssignments(responseProps);

        // Properties for create/update DTOs (mirrors CreateDtoGenerator/UpdateDtoGenerator logic)
        var createProps = BuildCreateProps(entity);
        var updateProps = BuildUpdateProps(entity);

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by CrudKit.SourceGen — do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System.Linq;");
        sb.AppendLine($"using {entity.Namespace};");
        sb.AppendLine($"using {entity.Namespace}.Dtos;");
        sb.AppendLine("using CrudKit.Core.Interfaces;");
        sb.AppendLine();
        sb.AppendLine($"namespace {entity.Namespace}.Mappers;");
        sb.AppendLine();
        sb.AppendLine($"/// <summary>Mapper for <see cref=\"{entity.Name}\"/>.</summary>");
        sb.AppendLine($"public sealed class {entity.Name}Mapper : {interfaceList}");
        sb.AppendLine("{");

        // --- IResponseMapper: Map() ---
        sb.AppendLine($"    public {entity.Name}Response Map({entity.Name} entity)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return new {entity.Name}Response(");

        for (int i = 0; i < assignments.Count; i++)
        {
            bool isLast = i == assignments.Count - 1;
            sb.Append($"            entity.{assignments[i]}");
            if (!isLast)
                sb.AppendLine(",");
            else
                sb.AppendLine(");");
        }

        sb.AppendLine("    }");
        sb.AppendLine();

        // --- IResponseMapper: Project() ---
        sb.AppendLine($"    public IQueryable<{entity.Name}Response> Project(IQueryable<{entity.Name}> query)");
        sb.AppendLine("    {");
        sb.AppendLine($"        return query.Select(entity => new {entity.Name}Response(");

        for (int i = 0; i < assignments.Count; i++)
        {
            bool isLast = i == assignments.Count - 1;
            sb.Append($"            entity.{assignments[i]}");
            if (!isLast)
                sb.AppendLine(",");
            else
                sb.AppendLine("));");
        }

        sb.AppendLine("    }");

        // --- ICreateMapper: FromCreateDto() ---
        if (hasCreate)
        {
            sb.AppendLine();
            sb.AppendLine($"    public {entity.Name} FromCreateDto(Create{entity.Name} dto)");
            sb.AppendLine("    {");
            sb.AppendLine($"        return new {entity.Name}");
            sb.AppendLine("        {");

            foreach (var p in createProps)
                sb.AppendLine($"            {p} = dto.{p},");

            sb.AppendLine("        };");
            sb.AppendLine("    }");
        }

        // --- IUpdateMapper: ApplyUpdate() ---
        if (hasUpdate)
        {
            sb.AppendLine();
            sb.AppendLine($"    public void ApplyUpdate({entity.Name} entity, Update{entity.Name} dto)");
            sb.AppendLine("    {");

            foreach (var p in updateProps)
            {
                // Optional<T> — only apply when HasValue
                sb.AppendLine($"        if (dto.{p}.HasValue) entity.{p} = dto.{p}.Value!;");
            }

            sb.AppendLine("    }");
        }

        sb.AppendLine("}");

        return sb.ToString();
    }

    // ---------------------------------------------------------------------------
    // Interface list builder
    // ---------------------------------------------------------------------------

    private static string BuildInterfaceList(EntityMetadata entity, bool hasCreate, bool hasUpdate)
    {
        string n    = entity.Name;
        string resp = $"IResponseMapper<{n}, {n}Response>";
        string cre  = $"ICreateMapper<{n}, Create{n}>";
        string upd  = $"IUpdateMapper<{n}, Update{n}>";
        string crud = $"ICrudMapper<{n}, Create{n}, Update{n}, {n}Response>";

        if (hasCreate && hasUpdate)
            return crud;

        if (!hasCreate && !hasUpdate)
            return resp;

        if (hasCreate)          // update disabled
            return $"{resp}, {cre}";

        return $"{resp}, {upd}"; // create disabled
    }

    // ---------------------------------------------------------------------------
    // Property list helpers
    // ---------------------------------------------------------------------------

    private static List<string> BuildResponseProps(EntityMetadata entity)
    {
        var props = new List<string> { "Id", "CreatedAt", "UpdatedAt" };

        if (entity.ImplementsISoftDeletable)
            props.Add("DeletedAt");

        if (entity.ImplementsIMultiTenant)
            props.Add("TenantId");

        foreach (var p in entity.Properties)
        {
            if (!p.IsSkipResponse)
                props.Add(p.Name);
        }

        return props;
    }

    private static List<string> BuildCreateProps(EntityMetadata entity)
    {
        var props = new List<string>();
        foreach (var p in entity.Properties)
        {
            if (!p.IsProtected)
                props.Add(p.Name);
        }
        return props;
    }

    private static List<string> BuildUpdateProps(EntityMetadata entity)
    {
        var props = new List<string>();
        foreach (var p in entity.Properties)
        {
            if (!p.IsProtected && !p.IsSkipUpdate)
                props.Add(p.Name);
        }
        return props;
    }

    private static List<string> BuildAssignments(List<string> propNames)
    {
        // Simple direct assignment — entity.PropName
        return propNames;
    }
}
