using System.Collections.Generic;
using System.Text;
using CrudKit.SourceGen.Models;

namespace CrudKit.SourceGen.Generators;

/// <summary>
/// Generates a <c>{Name}Response</c> positional record DTO.
/// Always emitted — even for ReadOnly entities.
/// Excludes properties marked with [SkipResponse].
/// Includes system fields (Id, CreatedAt, UpdatedAt) and optional soft-delete/tenant fields.
/// </summary>
internal static class ResponseDtoGenerator
{
    public static string Generate(EntityMetadata entity)
    {
        // Start with system fields that belong in the response
        var responseProps = new List<(string Type, string Name)>
        {
            ("Guid", "Id"),
            ("DateTime", "CreatedAt"),
            ("DateTime", "UpdatedAt"),
        };

        if (entity.ImplementsISoftDeletable)
            responseProps.Add(("DateTime?", "DeletedAt"));

        if (entity.ImplementsIMultiTenant)
            responseProps.Add(("string", "TenantId"));

        // Add user-defined properties, excluding [SkipResponse]
        foreach (var p in entity.Properties)
        {
            if (p.IsSkipResponse)
                continue;

            string typeName = p.IsNullable && !p.TypeName.EndsWith("?")
                ? p.TypeName + "?"
                : p.TypeName;

            responseProps.Add((typeName, p.Name));
        }

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by CrudKit.SourceGen — do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using System;");
        sb.AppendLine();
        sb.AppendLine($"namespace {entity.Namespace}.Dtos;");
        sb.AppendLine();
        sb.Append($"public sealed record {entity.Name}Response(");
        sb.AppendLine();

        for (int i = 0; i < responseProps.Count; i++)
        {
            var (type, name) = responseProps[i];
            bool isLast = i == responseProps.Count - 1;

            sb.Append($"    {type} {name}");
            if (!isLast)
                sb.AppendLine(",");
            else
                sb.AppendLine(");");
        }

        return sb.ToString();
    }
}
