using System.Collections.Generic;
using System.Text;
using CrudKit.SourceGen.Models;

namespace CrudKit.SourceGen.Generators;

/// <summary>
/// Generates an Update DTO positional record with <c>Optional&lt;T&gt;</c> wrapping, using the configured naming convention.
/// Returns <c>null</c> when the entity has updates disabled.
/// </summary>
internal static class UpdateDtoGenerator
{
    /// <summary>
    /// Builds the source text for the UpdateDto file.
    /// Returns <c>null</c> when no file should be emitted.
    /// </summary>
    public static string? Generate(EntityMetadata entity, NamingConvention naming)
    {
        if (!entity.IsUpdateEnabled)
            return null;

        // Properties eligible for UpdateDto: not system, not [Protected], not [SkipUpdate]
        var props = new List<PropertyMetadata>();
        foreach (var p in entity.Properties)
        {
            if (!p.IsProtected && !p.IsSkipUpdate)
                props.Add(p);
        }

        string className = naming.FormatUpdateDtoName(entity.Name);

        var sb = new StringBuilder();

        sb.AppendLine("// <auto-generated />");
        sb.AppendLine("// Generated by CrudKit.SourceGen — do not edit manually.");
        sb.AppendLine("#nullable enable");
        sb.AppendLine();
        sb.AppendLine("using CrudKit.Core.Models;");
        sb.AppendLine();
        sb.AppendLine($"namespace {entity.Namespace}.Dtos;");
        sb.AppendLine();
        sb.Append($"public sealed record {className}(");

        if (props.Count == 0)
        {
            sb.AppendLine(");");
        }
        else
        {
            sb.AppendLine();
            for (int i = 0; i < props.Count; i++)
            {
                var p = props[i];
                bool isLast = i == props.Count - 1;

                // Wrap in Optional<T> — nullable types stay nullable inside Optional
                string innerType = p.IsNullable && !p.TypeName.EndsWith("?")
                    ? p.TypeName + "?"
                    : p.TypeName;

                sb.Append($"    Optional<{innerType}> {p.Name} = default");

                if (!isLast)
                    sb.AppendLine(",");
                else
                    sb.AppendLine(");");
            }
        }

        return sb.ToString();
    }
}
